### ISSUE TITLE
Conversion Values for SPEED and ACC/DEC register values

### ISSUE THREAD

**Issue by darkinvolt** [ponoor/Ponoor_PowerSTEP01_Library#4]
Greetings,
first of all I would like to thank you for the great work that you did with this library.
I am currently working with a L6482 sm-driver and took a deep dive into the code and documentation.

Correct me if I am wrong, but shouldn't the conversion value for the SPEED register be 250*10^(-9)/2^(-28) =  67.109?
This would be represented in spdCalc and spdParse is a rather small difference.

On the other hand i was left with scratching my head in accCalc, accParse, decCalc, decParse - the value should be 0.0687 if I am not mistaken, yours is 0.137.., so double the value, which would alter the intended settings.

Would you check this please?

**Comment by kanta** [comment]
Hi,
This library is forked from the [Megunolink's repo](https://github.com/Megunolink/powerSTEP01_Arduino_Library) which forked from the [Sparkfun's repo](https://github.com/sparkfun/SparkFun_AutoDriver_Arduino_Library).
And actually these parts are from the original and I haven't looked deep inside of these values... But I found a same kind of issue from the original repo: https://github.com/sparkfun/SparkFun_AutoDriver_Arduino_Library/issues/4

Let me check.

**Comment by kanta** [comment]
Hi again @darkinvolt ,

I checked these values with the datasheet, and I believe you are right. With my calculation, the following table is the correct multiply values.

|Register name|to the register val|from the register val|
|:----|:----|:----|
|SPEED|67.108864|0.01490116119|
|ACC / DEC|0.06871947673|15.2587890625|
|MAX_SPEED|0.065536|15.2587890625|
|MIN_SPEED|4.194304|0.2384185791|
|FS_SPD|0.065536|15.2587890625|
|INT_SPEED|16.777216|0.05960464477|

`SPEED`, `INT_SPD`, `ACC` and `DEC` related values are wrong. I will come back here with an updated code. Thanks!

By the way, I noticed there is an inconsistency in the datasheet about `INT_SPD` and there is an official comment about it.
https://community.st.com/t5/power-management/calculate-stepss-for-powerstep01-and-l6480/m-p/251144

**Comment by kanta** [comment]
@darkinvolt 
I tested with a physical motor.
As you said, acceleration and deceleration took 2 times longer than expected.
Now I have updated the code and release it. Here is the diff.
https://github.com/ponoor/Ponoor_PowerSTEP01_Library/commit/b9af25d94acc8da1cb9b9fe3497e2f222d4e83d8#diff-7f5b5689b67ea528a73268de81ba9c9901d9db57aef97e52c30987f8711cedceR17

I'm going to close this issue, thank you!
